name: continual-calibration-env
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - colorama=0.4.6
  - comm=0.1.4
  - conda=23.1.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=40.0.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fmt=9.1.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.19.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.6.1
  - keyutils=1.6.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.40
  - libarchive=3.6.2
  - libcurl=7.88.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libiconv=1.17
  - libmamba=1.4.1
  - libmambapy=1.4.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libsodium=1.0.18
  - libsolv=0.7.23
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libuuid=2.38.1
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.4.1
  - matplotlib-inline=0.1.6
  - ncurses=6.3
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=4.1.0
  - pluggy=1.0.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.7
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pygments=2.17.2
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=25.1.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.28.2
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.7
  - setuptools=65.6.3
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.65.0
  - traitlets=5.14.1
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.12
  - wheel=0.40.0
  - xz=5.2.6
  - yaml-cpp=0.7.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zstandard=0.19.0
  - zstd=1.5.2
  - pip:
      - absl-py==2.0.0
      - appdirs==1.4.4
      - avalanche-lib==0.4.0
      - beautifulsoup4==4.12.2
      - cachetools==5.3.2
      - click==8.1.7
      - condacolab==0.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - dill==0.3.7
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.47.0
      - fsspec==2023.12.2
      - gdown==4.7.1
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - gputil==1.4.0
      - grpcio==1.60.0
      - jinja2==3.1.2
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - lightning-utilities==0.10.0
      - markdown==3.5.1
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - pillow==10.2.0
      - protobuf==4.23.4
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.1
      - pytorchcv==0.0.67
      - pyyaml==6.0.1
      - quadprog==0.1.11
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - sentry-sdk==1.39.1
      - setproctitle==1.3.3
      - smmap==5.0.1
      - soupsieve==2.5
      - sympy==1.12
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - torch==2.1.2
      - torchmetrics==1.2.1
      - torchvision==0.16.2
      - triton==2.1.0
      - typing-extensions==4.4.0
      - wandb==0.16.1
      - werkzeug==3.0.1
